
url: jdbc:sqlserver://rrhh.database.windows.net;database=RRHH;

user: stevebash

password: 1qaz"WSX
    
defaultRole: anonimo

secret: munilavictoria

port: 9090

jwtRoutines :
    - login

origin: http://localhost:8080

