
url: jdbc:sqlserver://172.168.200.11:1433;database=RRHH;

user: vadrianzenl

password: victor14270147
    
defaultRole: anonimo

secret: munilavictoria

port: 9090

jwtRoutines :
    - login

origin: http://172.168.200.4

