
url: jdbc:sqlserver://localhost:1433;database=xrest_test;

user: authenticator

schema: api

password: 2wsx!QAZ

defaultRole: anonymous

secret: munilavictoria

port: 9090

jwtRoutines :
    - login

origin: http://localhost:9090
