
url: jdbc:sqlserver://rrhh.database.windows.net:1433;database=RRHH;encrypt=true;trustServerCertificate=false;hostNameInCertificate=eastus1-a.control.database.windows.net;loginTimeout=30;

user: stevebash

password: 1qaz"WSX
    
defaultRole: planillero

port: 9090


