
CREATE TABLE dbo.item (
  id INT NOT NULL IDENTITY,
  CONSTRAINT item_pk PRIMARY KEY (id)
)
GO

CREATE TABLE dbo.actor (
  actor_id INT NOT NULL IDENTITY ,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  last_update DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT actor_pk PRIMARY KEY (actor_id)
)
GO

